[package]
name = "chessing"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.14.0"
fastrand = "2.3.0"
heapless = "0.8.0"
regex = "1.11.1"
rustc-hash = "2.1.1"

[profile.test]
inherits = "release"
